#!/bin/bash

usage() {
    echo "blades <pattern> <command>..."
    echo ""
    echo "<pattern> can be 'all'"
}

PATTERN="$1"
shift
case "$PATTERN" in
    all)
        PATTERN="^blade"
        ;;
    -h|-?|--help)
        usage
        exit
        ;;
esac

OK=0
NOT_OK=0

for BLADE in $(bhosts -w | grep -vP "closed_Adm|unavail" | grep "$PATTERN" | awk '{print $1}')
do
    SSH_OPTS=( -o 'StrictHostKeyChecking no' -o 'UserKnownHostsFile /dev/null' -o 'PasswordAuthentication no' )
    echo -n "==> $BLADE"
    OUTPUT=$(ssh "${SSH_OPTS[@]}" $BLADE "$@" 2> /dev/null)
    if [ $? -eq 0 ]
    then
        OK=$(( OK + 1 ))
        echo ' ok'
    else
        NOT_OK=$(( NOT_OK + 1 ))
        echo ' not ok'
    fi
    if [ -n "$OUTPUT" ]
    then
        echo "$OUTPUT"
    fi
done
if [ $OK -gt 0 ]
then
    echo "OK: $OK"
fi
if [ $NOT_OK -gt 0 ]
then
    echo "NOT OK: $NOT_OK"
fi
