#!/usr/bin/perl

use strict;
use warnings;

use DateTime::Format::Strptime;

my ($pattern, $time1, $time2) = @ARGV;
my $dt_format = DateTime::Format::Strptime->new(
    pattern   => $pattern,
    locale    => 'en_US',
    time_zone => 'America/Chicago',
    on_error  => 'croak',
) or die 'failed to create DateTime Formatter';
my $dt1 = $dt_format->parse_datetime($time1);
my $dt2 = $dt_format->parse_datetime($time2);
my $delta = $dt1->delta_ms($dt2);

if ($delta->hours > 24 || $delta->days || $delta->months || $delta->weeks) {
    print "ERROR: This is not accurate for times spanning days.\n";
    exit 1;
}

my $elapsed_seconds =
    $delta->hours * 3600
    + $delta->minutes * 60
    + $delta->seconds;
print "$elapsed_seconds\n";
