#!/usr/bin/env perl

use strict;
use warnings;

use lib qw(/gsc/scripts/opt/genome/lib);

use Snapshot qw();

my $snapshot = $ARGV[0];
my $snapshot_path;
if ($snapshot eq 'dev') {
    $snapshot_path = $ENV{HOME} . '/dev';
} else {
    $snapshot = "genome-$snapshot" unless $snapshot =~ /^genome-/;
    $snapshot_path = Snapshot::find_snapshot($snapshot);
}

$snapshot_path .= '/lib/perl/Genome';

print $snapshot_path;
