#!/bin/bash

set -o errexit
set -o nounset

init_gitsick_dir() {
    GITSICK_DIR="$(git config --global gitsick.dir || true)"
    if [ -z "$GITSICK_DIR" ]; then
        GITSICK_DIR="$HOME/.gitsick"
    fi
    if [ ! -d "$GITSICK_DIR" ]; then
        mkdir "$GITSICK_DIR"
    fi
}

main() {
    local HTTPS_URL="$1" NAME="$2" WORK_TREE="$3"

    if test -z "$WORK_TREE"; then
        WORK_TREE="$HOME"
    fi

    init_gitsick_dir
    local GIT_DIR="$GITSICK_DIR"/"$NAME".git
    if ! test -d "$GIT_DIR"
    then
        git clone --bare "$HTTPS_URL" "$GIT_DIR"
    fi
    (
        cd "$GIT_DIR"
        git --work-tree $WORK_TREE checkout master
    )
}

main "$@"
