#!/bin/bash

set -o errexit

init_gitsick_dir() {
    GITSICK_DIR="$(git config --global gitsick.dir || true)"
    if [ -z "$GITSICK_DIR" ]; then
        GITSICK_DIR="$HOME/.gitsick"
    fi
    if [ ! -d "$GITSICK_DIR" ]; then
        mkdir "$GITSICK_DIR"
    fi
}

main() {
    local HTTPS_URL="$1" NAME="$2" WORK_TREE="$3"

    if test -z "$WORK_TREE"; then
        WORK_TREE="$HOME"
    fi

    set -o nounset

    init_gitsick_dir
    local GIT_DIR="$GITSICK_DIR"/"$NAME".git
    if ! test -d "$GIT_DIR"
    then
        git clone --bare "$HTTPS_URL" "$GIT_DIR"
    fi

    (
        git --work-tree "$WORK_TREE" --git-dir "$GIT_DIR" reset --mixed master > /dev/null
        git --work-tree "$WORK_TREE" --git-dir "$GIT_DIR" ls-files --modified -z | while read -d $'\0' -r FILE
        do
            FILE="$WORK_TREE/$FILE"
            if test -f "$FILE"
            then
                if test -f "$FILE.bak"
                then
                    echo "$0: cannot backup file: $File"
                    exit 1
                fi
                mv --verbose --no-clobber "$FILE" "$FILE.bak"
            fi
        done
        git --work-tree "$WORK_TREE" --git-dir "$GIT_DIR" reset --hard master > /dev/null
    )
}

main "$@"
