#!/usr/bin/env perl

use strict;
use warnings;

BEGIN {
    # This allows the gmt command to self-serve as a tab completer for the bash shell.
    # When "gmt" is run by bash as a tab completer, the code below will service the
    # tab-completion request and then exit before doing any real work.
    # The code is in an eval to prevent problems on systems which do not have Getopt::Complete
    # installed.  The code is in a BEGIN block to ensure it still runs before anything else.
    if ($ENV{COMP_LINE}) {
        eval "use Getopt::Complete::Cache class => 'Genome::Site::WUGC::Command', above => 1;";
        exit if ($@);
    }
};

use above 'Genome';
use Genome::Site::WUGC::Command;
Genome::Site::WUGC::Command->execute_with_shell_params_and_exit();
