#!/usr/bin/env perl

my @dirs = @ARGV;

my $snapshot_basedir = $ENV{HOME} . '/snapshots';

my $genome_dir;
my $ur_dir;
my $workflow_dir;
my @unknown_dirs;
for my $dir (@dirs) {
    if ($dir =~ /\/genome\//) {
        $genome_dir = $dir;
    }
    elsif ($dir =~ /\/ur\//) {
        $ur_dir = $dir;
    }
    elsif ($dir =~ /\/workflow\//) {
        $workflow_dir = $dir;
    }
    else {
        push @unknown_dirs, $dir;
    }
}
$genome_dir     = $ENV{HOME} . '/git/clean/genome/lib/perl' unless ($genome_dir);
$ur_dir         = $ENV{HOME} . '/git/clean/ur/lib' unless ($ur_dir);
$workflow_dir   = $ENV{HOME} . '/git/clean/workflow/lib' unless ($workflow_dir);

if (@unknown_dirs) {
    die "Unknown dirs:\n" . join("\n", @unknown_dirs, "\n");
}
print "\nCreating snapshot from:\n";
print "$genome_dir\n$ur_dir\n$workflow_dir\n";

my $snapshot_dir = $snapshot_basedir . '/' . time;
`rsync --exclude .git -av $genome_dir/* $snapshot_dir/`;
`rsync --exclude .git -av $ur_dir/* $snapshot_dir/`;
`rsync --exclude .git -av $workflow_dir/* $snapshot_dir/`;

`cd $genome_dir && git show HEAD | head -n 1 | sed 's/commit/genome/' >> $snapshot_dir/revisions`;
`cd $ur_dir && git show HEAD | head -n 1 | sed 's/commit/ur/' >> $snapshot_dir/revisions`;
`cd $workflow_dir && git show HEAD | head -n 1 | sed 's/commit/workflow/' >> $snapshot_dir/revisions`;

print "\nSnapshot: $snapshot_dir\n";
