#!/usr/bin/env perl
use strict;
use warnings;

BEGIN {
        eval "use Getopt::Complete::Cache class => 'UR::Namespace::Command', above => 1;";
};

use above "UR";

UR::Namespace::Command->execute_with_shell_params_and_exit();

=pod

=head1 NAME

ur

=head1 DESCRIPTION

The "ur" command is the entry point for a suite of tools to manage a UR project.

It also includes some built-in UR services.

Every command and sub-command supports the --help option.

=head1 SOFTWARE MODULE API

Looking for the docs on UR.pm?  

Try "perldoc UR.pm" or "man UR".  On some systems (Mac),
perldoc will show this page for both "perldoc ur" and also "perldoc UR" due to
filesystem case insensitivity.

=head1 OPTIONS

These depend on the specific sub-command.  Use ur SOMESUBCOMMAND --help for more details on a specific command.

=head1 DEVELOPER NOTE

Running this WITHIN a source tree under the Genome namespace will automatically "use lib" your tree.

A message will appear to STDERR when this occurs.

=head1 BUGS

Report bugs at http:://urobject.sourceforge.net 

=head1 AUTHOR

Scott Smith (sakoht)

 at cpan.org

=cut


