#!/usr/bin/env perl

use strict;
use warnings;

use Cwd qw(cwd abs_path);

my $src_host = 'nnutter-mbp.no-ip.org';
my $dest_host = 'linus264.gsc.wustl.edu';
my $home_dir = $ENV{HOME};
my $src_dir = "$home_dir/Code/Genome/";
my $dest_dir = '~/tmp/genome/macbook/';

unless (-d $src_dir) {
    die "Source directory is not a directory ($src_dir)";
}

unless ($dest_dir && length($dest_dir) > 2) {
    die "Destination directory is not expected ($dest_dir)";
}

my $cwd = cwd() . '/';
if ($cwd !~ /$src_dir/) {
    die "Not in configured source directory ($cwd !~ /$src_dir/)";
}

my $rsync_cmd = "rsync --exclude '*.swp' --delete -av $src_dir $dest_host:$dest_dir";
my $rsync_exit = system($rsync_cmd);
unless ($rsync_exit == 0) {
    die 'Failed to complete rsync';
}
