#!/usr/bin/env bash

HOST="linus264.gsc.wustl.edu"
if [ "$1" == "-t" ]; then
    shift
    HOST="$1"
    shift
fi

IP_ADDR=$(dig +short ${HOST})

if [ -z "$IP_ADDR" ]; then
    ssh -At wugsc.wustl.edu ssh -At $HOST $*
else
    ssh -At $HOST $*
fi
