#!/bin/bash

URL_HOST="apipe-ci.gsc.wustl.edu"

URL_PREFIX="https://$URL_HOST/job/"
URL_SUFFIX="/lastCompletedBuild/api/xml"

function fetch_snapshot {
    SNAPSHOT_PATH=$(readlink /gsc/scripts/opt/genome/current/user)
    echo ${SNAPSHOT_PATH/*\//}
}

function color_on_status {
    local BG, FG
    case $2 in
        FAILURE)  BG='white';   FG='red' ;;
        UNSTABLE) BG='yellow';  FG='black' ;;
        SUCCESS)  BG='default'; FG='blue'  ;;
        ABORTED)  BG='black';   FG='white' ;;
    esac
    echo "#[bg=$BG, fg=$FG]${1}#[default]"
}

function fetch_job_status {
    local TEST_QUERY="?xpath=/${1}/result"
    echo $(curl -sk ${URL_PREFIX}${2}${URL_SUFFIX}${TEST_QUERY} | perl -ne '/result>([^<]*)/ && print "$1";')
}

function job_status {
    local TESTS
    if dig $URL_HOST +short | grep -q .; then
        if hash curl 2> /dev/null; then
            STATUS=$(fetch_job_status "$@")
            TEST=$(color_on_status "${STATUS:0:1}" $STATUS)
            if [ -z "$TESTS" ]; then
                TESTS=$TEST
            else
                TESTS=${TESTS}${TEST}
            fi
            echo -n "${TESTS}"
        fi
    fi
}

function count_gerrit_query {
    local GERRIT_HOST=apipe-review.gsc.wustl.edu
    if dig $GERRIT_HOST +short | grep -q .; then
        local COUNT="$(ssh -o 'ConnectTimeout 3' -p 29418 $GERRIT_HOST gerrit query "$@" 2> /dev/null | grep ^rowCount | cut -d ' ' -f 2)"
        if [ -z "$COUNT" ]; then
            COUNT=$(color_on_status 'T' 'FAILURE')
        fi
        echo -n "$COUNT"
    fi
}

function cache {
    local CACHE_DIR="$HOME/.cache/tmux_status"
    for A in "$@"; do
        CACHE_DIR="${CACHE_DIR}/$A"
    done
    mkdir -p $CACHE_DIR

    local NOW=$(date +"%s")

    local CACHE_FILE="${CACHE_DIR}/DATA"

    local MODDATE="$NOW"
    if [ -e "$CACHE_FILE" ]; then
        MODDATE=$(stat -c %y "$CACHE_FILE")
        MODDATE=${MODDATE%% *}
    fi

    if (( $MODDATE + 300 > $NOW )); then
        local DATA=$("$@")
        echo -n "$DATA" > "$CACHE_FILE"
    fi

    cat "$CACHE_FILE"
}

function separator {
    echo -n ' 〉'
}

separator
cache count_gerrit_query 'status:open'
echo -n ' '
cache job_status matrixBuild '0-Genome-Perl-Tests-Quick'
cache job_status matrixBuild '1-Genome-Perl-Tests'
cache job_status freeStyleBuild '2-Genome-Model-Tests'
separator
