# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[docker_context]
disabled = true

[gcloud]
disabled = true

[git_branch]
format = 'on [$branch(:$remote_branch)]($style) '

[git_status]
disabled = true

[golang]
disabled = true

[lua]
disabled = true

[package]
disabled = true

[perl]
disabled = true

[python]
disabled = true
